version: '3.9'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,dynamodb,cloudformation,sts,ssm,iam,kms,lambda,apigateway,wafv2,firehose
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./src/script/logging-bucket.sh:/usr/src/app/logging-bucket.sh
      - ./init.sh:/usr/src/app/init.sh
    # entrypoint: ["/bin/sh", "-c", "/usr/src/app/init.sh"]